/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-tipc
// biome-ignore lint: disable
export {}

declare module '@byc/tipc' {
  interface TipcInvokeExpose {
    config: typeof import('./index.ts')['configTipcSchema']['handlers']
    image: typeof import('./index.ts')['imageTipcSchema']['handlers']
  }

  interface TipcListenerExpose {
    config: typeof import('./index.ts')['configTipcSchema']['listeners']
    image: typeof import('./index.ts')['imageTipcSchema']['listeners']
  }
}
