/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    NameDisplay: typeof import('./src/components/NameDisplay.vue')['default']
    WindowHeader: typeof import('./src/components/WindowHeader.vue')['default']
    WindowNav: typeof import('./src/components/WindowNav.vue')['default']
  }
}
